services:
  - type: web
    name: junsvoca
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        sync: false
